name: Vercel Production Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Next.js build
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Create GitHub Deployment
        id: deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ github.token }}
          environment: production
          ref: ${{ github.sha }}

      - name: Deploy to Vercel (Production)
        id: vercel
        run: |
          url=$(vercel deploy \
            --token $VERCEL_TOKEN \
            --yes \
            --scope $VERCEL_ORG_ID \)
          echo "preview_url=$url" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Set Deployment Status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          state: success
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          environment-url: ${{ steps.vercel.outputs.prod_url }}
